// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIbwDKlx7qwU1HkdduTpd3Hd8b0-Uft0k',
    appId: '1:718672488288:web:3d135bf8f69ff7cef86005',
    messagingSenderId: '718672488288',
    projectId: 'tragnambo-notification',
    authDomain: 'tragnambo-notification.firebaseapp.com',
    storageBucket: 'tragnambo-notification.firebasestorage.app',
    measurementId: 'G-SJ9PGEZ9M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPRZ24VJGzooU46jwTcG4JxEVsn99_324',
    appId: '1:718672488288:android:dfac47a22f47adf5f86005',
    messagingSenderId: '718672488288',
    projectId: 'tragnambo-notification',
    storageBucket: 'tragnambo-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7zSUk7m2O-MTUYP9zRTbTT7bQ_4XfVU',
    appId: '1:718672488288:ios:cb419c2d2cef15ccf86005',
    messagingSenderId: '718672488288',
    projectId: 'tragnambo-notification',
    storageBucket: 'tragnambo-notification.firebasestorage.app',
    iosBundleId: 'com.example.loginWithUniteTestAndCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7zSUk7m2O-MTUYP9zRTbTT7bQ_4XfVU',
    appId: '1:718672488288:ios:cb419c2d2cef15ccf86005',
    messagingSenderId: '718672488288',
    projectId: 'tragnambo-notification',
    storageBucket: 'tragnambo-notification.firebasestorage.app',
    iosBundleId: 'com.example.loginWithUniteTestAndCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIbwDKlx7qwU1HkdduTpd3Hd8b0-Uft0k',
    appId: '1:718672488288:web:2def03fbd724a0f5f86005',
    messagingSenderId: '718672488288',
    projectId: 'tragnambo-notification',
    authDomain: 'tragnambo-notification.firebaseapp.com',
    storageBucket: 'tragnambo-notification.firebasestorage.app',
    measurementId: 'G-EX304NEJFN',
  );
}
